language: node_js
node_js:
  - stable
cache:
  directories:
    - "node_modules"
sudo: required
install:
  - sudo apt-get update
  - sudo apt-get -y install software-properties-common
  - sudo apt-add-repository -y ppa:ansible/ansible
  - sudo apt-get update
  - sudo apt-get install -y ansible
  - npm ci
script:
  - npm run test
  - npm run build:lib