version: '3'

volumes:
  nginx-srv:

services:

  nginx:
    build: ./nginx
    depends_on:
      - storybook
    ports:
      - 80:80   # http
      - 443:443 # https
    volumes:
      - nginx-srv:/srv/storybook
    command:
      - nginx

  # Build container.
  # It builds the storybook, puts it in a shared volume for nginx and exits
  storybook:
    build: .
    volumes:
      - nginx-srv:/srv/storybook/storybook-static